server:
  port: 8083


spring:
  datasource:
    db1:
      jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root


    db2:
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root


#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#



#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.jyl.model
#

#替换mybatis-config.xml
#驱动默认是 com.mysql.jdbc.Driver
#  jpa:
#    #自动创建|更新|验证数据库表结构
#    hibernate:
#      ddl-auto: update
#    #设置数据库引擎为InnoDB
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    #打印sql语句，方便调试
#    show-sql: true

